apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cascade
  namespace: argocd
spec:
  description: Cascade data-platform control plane
  sourceRepos:
    - https://github.com/Talif787/cascade.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: cascade
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: true
